### ISSUE TITLE
FEATURE:  Global Content Block (or the similar)

### ISSUE THREAD

**Issue by nick22222** [pratermade/ss-cms#10]
Global Content Block add-on for each page.  Similar to CMSMS, I was able to create a content block (some sort of database entry) and then be able to call any entry up on a page.
`{global_content name='zPAGE-DISCLAIMER_4_links'}` 
or
`{global_content name='JS and CSS for Video Light Box Fancy'}`

Also, on that same note... the ListIt plugin was also called up using this type of feature:
`{ListIt2employees summarytemplate="DEPT-Executive_Council" item="$page_alias"}`

**Comment by pratermade** [comment]
All done. New dict add to global context called global_content. New content can be added in global_content table.

**Comment by nick22222** [comment]
Global Content works great on the .html files!
Is there a way to add global_content within the article block?
Or is the best way to accomplish this is to list all available global_blocks to choose, instead of within the article block, on the user side?
