### ISSUE TITLE
FILE_BROWSER.HTML extension options

### ISSUE THREAD

**Issue by nick22222** [pratermade/ss-cms#40]
Here are the options for file extensions... (I removed most of what we do not need... you can pick and choose from this list)

/* Core Styles */
.jqueryFileTree LI.directory { background: url(images/directory.png) left top no-repeat; }
.jqueryFileTree LI.expanded { background: url(images/folder_open.png) left top no-repeat; }
.jqueryFileTree LI.file { background: url(images/file.png) left top no-repeat; }
.jqueryFileTree LI.wait { background: url(images/spinner.gif) left top no-repeat; }
/* File Extensions*/
.jqueryFileTree LI.ext_avi { background: url(images/film.png) left top no-repeat; }
.jqueryFileTree LI.ext_bmp { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_css { background: url(images/css.png) left top no-repeat; }
.jqueryFileTree LI.ext_doc { background: url(images/doc.png) left top no-repeat; }
.jqueryFileTree LI.ext_exe { background: url(images/application.png) left top no-repeat; }
.jqueryFileTree LI.ext_gif { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_htm { background: url(images/html.png) left top no-repeat; }
.jqueryFileTree LI.ext_html { background: url(images/html.png) left top no-repeat; }
.jqueryFileTree LI.ext_jpg { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_jpeg { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_js { background: url(images/script.png) left top no-repeat; }
.jqueryFileTree LI.ext_lasso { background: url(images/code.png) left top no-repeat; }
.jqueryFileTree LI.ext_log { background: url(images/txt.png) left top no-repeat; }
.jqueryFileTree LI.ext_m4p { background: url(images/music.png) left top no-repeat; }
.jqueryFileTree LI.ext_mov { background: url(images/film.png) left top no-repeat; }
.jqueryFileTree LI.ext_mp3 { background: url(images/music.png) left top no-repeat; }
.jqueryFileTree LI.ext_mp4 { background: url(images/film.png) left top no-repeat; }
.jqueryFileTree LI.ext_mpg { background: url(images/film.png) left top no-repeat; }
.jqueryFileTree LI.ext_mpeg { background: url(images/film.png) left top no-repeat; }
.jqueryFileTree LI.ext_ogg { background: url(images/music.png) left top no-repeat; }
.jqueryFileTree LI.ext_pdf {background: url(images/pdf.png) 0 4px no-repeat;}
.jqueryFileTree LI.ext_php { background: url(images/php.png) left top no-repeat; }
.jqueryFileTree LI.ext_png { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_ppt { background: url(images/ppt.png) left top no-repeat; }
.jqueryFileTree LI.ext_psd { background: url(images/psd.png) left top no-repeat; }
.jqueryFileTree LI.ext_py { background: url(images/script.png) left top no-repeat; }
.jqueryFileTree LI.ext_sql { background: url(images/db.png) left top no-repeat; }
.jqueryFileTree LI.ext_tif { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_tiff { background: url(images/picture.png) left top no-repeat; }
.jqueryFileTree LI.ext_txt { background: url(images/txt.png) left top no-repeat; }
.jqueryFileTree LI.ext_wav { background: url(images/music.png) left top no-repeat; }
.jqueryFileTree LI.ext_wmv { background: url(images/film.png) left top no-repeat; }
.jqueryFileTree LI.ext_xls { background: url(images/xls.png) left top no-repeat; }
.jqueryFileTree LI.ext_xml { background: url(images/code.png) left top no-repeat; }
.jqueryFileTree LI.ext_zip { background: url(images/zip.png) left top no-repeat; }

**Comment by pratermade** [comment]
What is an example of the end result? How do you want me to generate the html?

**Comment by pratermade** [comment]
For example, what is this:

<li class="file2 ext_gif2"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail"><img src="{}">{}</a></li>

supposed to look like?

**Comment by nick22222** [comment]
Like this:

<li class="file ext_jpg"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
Or 
<li class="file ext_pdf"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
Or
<li class="file ext_doc"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>

The li class has a fall back of FILE and an EXT_(file extension) based on what file it is.

**Comment by nick22222** [comment]
Not sure if you can read:

'''
<li class="file ext_pdf"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
'''
Or
'''
<li class="file ext_doc"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
'''
Or
'''
<li class="file ext_jpg"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
'''

**Comment by nick22222** [comment]
Fack, hard to do this on the phone
```
<li class="file ext_doc"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
```
Or 
```
<li class="file ext_pdf"><a href="#" thumbnail="{}" rel="{}" class="image_thumbnail">{}</a></li>
```

**Comment by pratermade** [comment]
Done and done.
