### ISSUE TITLE
Breadcrumbs current page title

### ISSUE THREAD

**Issue by nick22222** [pratermade/ss-cms#9]
Breadcrumbs do not need to show the current page, we need to add "current page title" to  global template so we can fix the breadcrumbs as shown:

{% for breadcrumb in breadcrumbs %}
    <a href="{% url 'page' breadcrumb.slug %}" class="breadcrumbs">{{ breadcrumb.title }}</a>&nbsp;<span>></span>&nbsp;{{ currentpagetitle }}
{% endfor %}

**Comment by pratermade** [comment]
What is wrong with providing the page title in the breadcrumbs?
